name: Bandit

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install bandit
      - run: bandit -r . -f html -o report.html --exit-zero
      - uses: actions/upload-artifact@v4
        with:
           name: report
           path: report.html
      
